/*
 * Legacy Vietnamese schema retained for design reference only.
 * The executable PostgreSQL schema used by the application starts below.
 *
CREATE TABLE "HangHangKhong" (
  "MaHang" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TenHang" VARCHAR(150) NOT NULL,
  "MaIATA" VARCHAR(10) UNIQUE,
  "QuocGia" VARCHAR(100),
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "SanBay" (
  "MaSanBay" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TenSanBay" VARCHAR(200) NOT NULL,
  "MaIATA" VARCHAR(10) UNIQUE,
  "ThanhPho" VARCHAR(100),
  "QuocGia" VARCHAR(100),
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "MayBay" (
  "MaMayBay" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SoHieu" VARCHAR(50) UNIQUE NOT NULL,
  "LoaiMayBay" VARCHAR(100),
  "SoGhe" INT NOT NULL CHECK ("SoGhe" > 0),
  "MaHang" INT NOT NULL,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ChuyenBay" (
  "MaChuyenBay" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SoHieuChuyenBay" VARCHAR(20) NOT NULL UNIQUE,
  "MaMayBay" INT NOT NULL,
  "SanBayDi" INT NOT NULL,
  "SanBayDen" INT NOT NULL,
  "ThoiGianKhoiHanh" TIMESTAMP NOT NULL,
  "ThoiGianDen" TIMESTAMP,
  "TrangThai" VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_chuyen_bay_san_bay" CHECK ("SanBayDi" <> "SanBayDen"),
  CONSTRAINT "chk_chuyen_bay_thoi_gian" CHECK ("ThoiGianDen" IS NULL OR "ThoiGianDen" > "ThoiGianKhoiHanh")
);

CREATE TABLE "HangGhe" (
  "MaHangGhe" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TenHangGhe" VARCHAR(50) NOT NULL UNIQUE,
  "MoTa" VARCHAR(300)
);

CREATE TABLE "GiaVe" (
  "MaGiaVe" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaChuyenBay" INT NOT NULL,
  "MaHangGhe" INT NOT NULL,
  "Gia" NUMERIC(18,2) NOT NULL CHECK ("Gia" >= 0),
  "SoLuongVe" INT NOT NULL CHECK ("SoLuongVe" >= 0),
  CONSTRAINT "uq_giave_chuyenbay_hangghe" UNIQUE ("MaChuyenBay", "MaHangGhe")
);

CREATE TABLE "KhachHang" (
  "MaKhachHang" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "HoTen" VARCHAR(150) NOT NULL,
  "NgaySinh" DATE,
  "GioiTinh" VARCHAR(20),
  "CCCD" VARCHAR(20) UNIQUE,
  "HoChieu" VARCHAR(30) UNIQUE,
  "SoDienThoai" VARCHAR(15) UNIQUE,
  "Email" VARCHAR(150) UNIQUE,
  "DiaChi" VARCHAR(250),
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "DatVe" (
  "MaDatVe" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaKhachHang" INT NOT NULL,
  "MaChuyenBay" INT NOT NULL,
  "MaHangGhe" INT NOT NULL,
  "NgayDat" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "SoLuong" INT NOT NULL DEFAULT 1 CHECK ("SoLuong" > 0),
  "TongTien" NUMERIC(18,2) NOT NULL CHECK ("TongTien" >= 0),
  "TrangThai" VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_datve_trangthai" CHECK ("TrangThai" IN ('PENDING', 'PAID', 'CANCELLED'))
);

CREATE TABLE "VeMayBay" (
  "MaVe" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaDatVe" INT NOT NULL,
  "MaKhachHang" INT NOT NULL,
  "SoGhe" VARCHAR(10),
  "MaVeDienTu" VARCHAR(100) UNIQUE,
  "TrangThai" VARCHAR(50) NOT NULL DEFAULT 'ISSUED',
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_ve_trangthai" CHECK ("TrangThai" IN ('ISSUED', 'USED', 'VOID'))
);

CREATE TABLE "ThanhToan" (
  "MaThanhToan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaDatVe" INT NOT NULL,
  "NgayThanhToan" TIMESTAMP,
  "SoTien" NUMERIC(18,2) NOT NULL CHECK ("SoTien" >= 0),
  "PhuongThuc" VARCHAR(50),
  "TrangThai" VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_thanhtoan_trangthai" CHECK ("TrangThai" IN ('PENDING', 'SUCCESS', 'FAILED'))
);

CREATE TABLE "TaiKhoan" (
  "MaTaiKhoan" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaKhachHang" INT,
  "TenDangNhap" VARCHAR(100) UNIQUE NOT NULL,
  "MatKhau" VARCHAR(255) NOT NULL,
  "VaiTro" VARCHAR(50) NOT NULL DEFAULT 'USER',
  "TrangThai" VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_taikhoan_vaitro" CHECK ("VaiTro" IN ('ADMIN', 'STAFF', 'USER')),
  CONSTRAINT "chk_taikhoan_trangthai" CHECK ("TrangThai" IN ('ACTIVE', 'LOCKED', 'DELETED'))
);

ALTER TABLE "MayBay"
  ADD CONSTRAINT "fk_maybay_hanghangkhong"
  FOREIGN KEY ("MaHang") REFERENCES "HangHangKhong" ("MaHang")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "ChuyenBay"
  ADD CONSTRAINT "fk_chuyenbay_maybay"
  FOREIGN KEY ("MaMayBay") REFERENCES "MayBay" ("MaMayBay")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "ChuyenBay"
  ADD CONSTRAINT "fk_chuyenbay_sanbaydi"
  FOREIGN KEY ("SanBayDi") REFERENCES "SanBay" ("MaSanBay")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "ChuyenBay"
  ADD CONSTRAINT "fk_chuyenbay_sanbayden"
  FOREIGN KEY ("SanBayDen") REFERENCES "SanBay" ("MaSanBay")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "GiaVe"
  ADD CONSTRAINT "fk_giave_chuyenbay"
  FOREIGN KEY ("MaChuyenBay") REFERENCES "ChuyenBay" ("MaChuyenBay")
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "GiaVe"
  ADD CONSTRAINT "fk_giave_hangghe"
  FOREIGN KEY ("MaHangGhe") REFERENCES "HangGhe" ("MaHangGhe")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "DatVe"
  ADD CONSTRAINT "fk_datve_khachhang"
  FOREIGN KEY ("MaKhachHang") REFERENCES "KhachHang" ("MaKhachHang")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "DatVe"
  ADD CONSTRAINT "fk_datve_chuyenbay"
  FOREIGN KEY ("MaChuyenBay") REFERENCES "ChuyenBay" ("MaChuyenBay")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "DatVe"
  ADD CONSTRAINT "fk_datve_hangghe"
  FOREIGN KEY ("MaHangGhe") REFERENCES "HangGhe" ("MaHangGhe")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "VeMayBay"
  ADD CONSTRAINT "fk_vemaybay_datve"
  FOREIGN KEY ("MaDatVe") REFERENCES "DatVe" ("MaDatVe")
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "VeMayBay"
  ADD CONSTRAINT "fk_vemaybay_khachhang"
  FOREIGN KEY ("MaKhachHang") REFERENCES "KhachHang" ("MaKhachHang")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "ThanhToan"
  ADD CONSTRAINT "fk_thanhtoan_datve"
  FOREIGN KEY ("MaDatVe") REFERENCES "DatVe" ("MaDatVe")
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "TaiKhoan"
  ADD CONSTRAINT "fk_taikhoan_khachhang"
  FOREIGN KEY ("MaKhachHang") REFERENCES "KhachHang" ("MaKhachHang")
  ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX "idx_chuyenbay_khoihanh" ON "ChuyenBay" ("ThoiGianKhoiHanh");
CREATE INDEX "idx_chuyenbay_sanbaydi" ON "ChuyenBay" ("SanBayDi");
CREATE INDEX "idx_chuyenbay_sanbayden" ON "ChuyenBay" ("SanBayDen");
CREATE INDEX "idx_datve_trangthai" ON "DatVe" ("TrangThai");
CREATE INDEX "idx_thanhtoan_trangthai" ON "ThanhToan" ("TrangThai");
*/

-- Flight Ticket Management System - PostgreSQL 16
-- Single executable source for schema initialization and reference seed data.

BEGIN;

CREATE TABLE IF NOT EXISTS airlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    iata_code VARCHAR(3) NOT NULL UNIQUE,
    country VARCHAR(100),
    cabin_baggage_kg INTEGER NOT NULL DEFAULT 7 CHECK (cabin_baggage_kg BETWEEN 0 AND 30),
    included_checked_baggage_kg INTEGER NOT NULL DEFAULT 0 CHECK (included_checked_baggage_kg BETWEEN 0 AND 100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_airlines_iata_code CHECK (iata_code = UPPER(iata_code))
);

ALTER TABLE airlines ADD COLUMN IF NOT EXISTS cabin_baggage_kg INTEGER NOT NULL DEFAULT 7;
ALTER TABLE airlines ADD COLUMN IF NOT EXISTS included_checked_baggage_kg INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS baggage_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airline_id BIGINT NOT NULL REFERENCES airlines(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    weight_kg INTEGER NOT NULL CHECK (weight_kg BETWEEN 1 AND 100),
    price NUMERIC(18, 2) NOT NULL CHECK (price >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_baggage_options_airline_weight UNIQUE (airline_id, weight_kg)
);

CREATE TABLE IF NOT EXISTS airports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    iata_code VARCHAR(3) NOT NULL UNIQUE,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_airports_iata_code CHECK (iata_code = UPPER(iata_code))
);

CREATE TABLE IF NOT EXISTS aircraft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(20) NOT NULL UNIQUE,
    model VARCHAR(100) NOT NULL,
    seat_capacity INTEGER NOT NULL CHECK (seat_capacity > 0),
    airline_id BIGINT NOT NULL REFERENCES airlines(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(20) NOT NULL,
    aircraft_id BIGINT NOT NULL REFERENCES aircraft(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    departure_airport_id BIGINT NOT NULL REFERENCES airports(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    arrival_airport_id BIGINT NOT NULL REFERENCES airports(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    departure_time TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_flights_number_departure UNIQUE (flight_number, departure_time),
    CONSTRAINT chk_flights_airports CHECK (departure_airport_id <> arrival_airport_id),
    CONSTRAINT chk_flights_time CHECK (arrival_time > departure_time),
    CONSTRAINT chk_flights_status CHECK (status IN ('SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'CANCELLED', 'DELAYED'))
);

CREATE TABLE IF NOT EXISTS fare_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS flight_fares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL REFERENCES flights(id) ON UPDATE CASCADE ON DELETE CASCADE,
    fare_class_id BIGINT NOT NULL REFERENCES fare_classes(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    price NUMERIC(18, 2) NOT NULL CHECK (price >= 0),
    seat_quota INTEGER NOT NULL CHECK (seat_quota >= 0),
    available_seats INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_flight_fares_flight_class UNIQUE (flight_id, fare_class_id),
    CONSTRAINT chk_flight_fares_available CHECK (available_seats BETWEEN 0 AND seat_quota)
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(20),
    citizen_id VARCHAR(20) UNIQUE,
    passport_number VARCHAR(30) UNIQUE,
    phone VARCHAR(20) UNIQUE,
    email VARCHAR(150) UNIQUE,
    address VARCHAR(250),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT UNIQUE REFERENCES customers(id) ON UPDATE CASCADE ON DELETE SET NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_accounts_role CHECK (role IN ('ADMIN', 'STAFF', 'USER')),
    CONSTRAINT chk_accounts_status CHECK (status IN ('ACTIVE', 'LOCKED', 'DELETED'))
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code VARCHAR(12) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    flight_id BIGINT NOT NULL REFERENCES flights(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    fare_class_id BIGINT NOT NULL REFERENCES fare_classes(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    booked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    passenger_count INTEGER NOT NULL DEFAULT 1 CHECK (passenger_count > 0),
    total_amount NUMERIC(18, 2) NOT NULL CHECK (total_amount >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_bookings_status CHECK (status IN ('PENDING', 'PAID', 'REFUND_REQUESTED', 'REFUNDED', 'CANCELLED', 'EXPIRED'))
);

CREATE TABLE IF NOT EXISTS booking_passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON UPDATE CASCADE ON DELETE CASCADE,
    full_name VARCHAR(150) NOT NULL,
    document_number VARCHAR(30),
    seat_number VARCHAR(10),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE booking_passengers ADD COLUMN IF NOT EXISTS seat_number VARCHAR(10);
ALTER TABLE booking_passengers ADD COLUMN IF NOT EXISTS checked_baggage_kg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE booking_passengers ADD COLUMN IF NOT EXISTS baggage_price NUMERIC(18, 2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON UPDATE CASCADE ON DELETE CASCADE,
    passenger_name VARCHAR(150) NOT NULL,
    passenger_document VARCHAR(30),
    seat_number VARCHAR(10),
    electronic_ticket_code VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ISSUED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tickets_booking_seat UNIQUE (booking_id, seat_number),
    CONSTRAINT chk_tickets_status CHECK (status IN ('ISSUED', 'USED', 'VOID'))
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON UPDATE CASCADE ON DELETE CASCADE,
    transaction_code VARCHAR(100) UNIQUE,
    paid_at TIMESTAMP WITH TIME ZONE,
    amount NUMERIC(18, 2) NOT NULL CHECK (amount >= 0),
    method VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_payments_method CHECK (method IN ('BANK_TRANSFER', 'CARD', 'E_WALLET')),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'SUCCESS', 'REFUNDED', 'FAILED'))
);

-- Keep existing official databases compatible when this script is executed again.
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS chk_bookings_status;
ALTER TABLE bookings ADD CONSTRAINT chk_bookings_status
    CHECK (status IN ('PENDING', 'PAID', 'REFUND_REQUESTED', 'REFUNDED', 'CANCELLED', 'EXPIRED'));
ALTER TABLE payments DROP CONSTRAINT IF EXISTS chk_payments_status;
ALTER TABLE payments ADD CONSTRAINT chk_payments_status
    CHECK (status IN ('PENDING', 'SUCCESS', 'REFUNDED', 'FAILED'));

CREATE INDEX IF NOT EXISTS idx_flights_route_departure ON flights(departure_airport_id, arrival_airport_id, departure_time);
CREATE INDEX IF NOT EXISTS idx_flights_status ON flights(status);
CREATE INDEX IF NOT EXISTS idx_bookings_customer ON bookings(customer_id, booked_at DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_booking_passengers_booking ON booking_passengers(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_booking ON payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);

INSERT INTO airlines (name, iata_code, country) VALUES
    ('Vietnam Airlines', 'VN', 'Vietnam'),
    ('VietJet Air', 'VJ', 'Vietnam'),
    ('Bamboo Airways', 'QH', 'Vietnam')
ON CONFLICT (iata_code) DO NOTHING;

UPDATE airlines SET cabin_baggage_kg = 7, included_checked_baggage_kg = 0
WHERE iata_code IN ('VN', 'VJ', 'QH');

INSERT INTO baggage_options (airline_id, weight_kg, price)
SELECT id, package.weight_kg, package.price FROM airlines
CROSS JOIN (VALUES (15, 180000::NUMERIC), (20, 240000::NUMERIC), (30, 360000::NUMERIC)) AS package(weight_kg, price)
WHERE iata_code = 'VN' ON CONFLICT (airline_id, weight_kg) DO NOTHING;
INSERT INTO baggage_options (airline_id, weight_kg, price)
SELECT id, package.weight_kg, package.price FROM airlines
CROSS JOIN (VALUES (15, 210000::NUMERIC), (20, 270000::NUMERIC), (30, 420000::NUMERIC)) AS package(weight_kg, price)
WHERE iata_code = 'VJ' ON CONFLICT (airline_id, weight_kg) DO NOTHING;
INSERT INTO baggage_options (airline_id, weight_kg, price)
SELECT id, package.weight_kg, package.price FROM airlines
CROSS JOIN (VALUES (15, 190000::NUMERIC), (20, 250000::NUMERIC), (30, 380000::NUMERIC)) AS package(weight_kg, price)
WHERE iata_code = 'QH' ON CONFLICT (airline_id, weight_kg) DO NOTHING;

INSERT INTO airports (name, iata_code, city, country, timezone) VALUES
    ('Noi Bai International Airport', 'HAN', 'Ha Noi', 'Vietnam', 'Asia/Ho_Chi_Minh'),
    ('Tan Son Nhat International Airport', 'SGN', 'Ho Chi Minh City', 'Vietnam', 'Asia/Ho_Chi_Minh'),
    ('Da Nang International Airport', 'DAD', 'Da Nang', 'Vietnam', 'Asia/Ho_Chi_Minh')
ON CONFLICT (iata_code) DO NOTHING;

INSERT INTO fare_classes (code, name, description) VALUES
    ('ECONOMY', 'Economy', 'Standard economy class'),
    ('BUSINESS', 'Business', 'Business class with priority services')
ON CONFLICT (code) DO NOTHING;

INSERT INTO aircraft (registration_number, model, seat_capacity, airline_id)
SELECT 'VN-A888', 'Airbus A321', 184, id FROM airlines WHERE iata_code = 'VN'
ON CONFLICT (registration_number) DO NOTHING;

INSERT INTO aircraft (registration_number, model, seat_capacity, airline_id)
SELECT 'VN-A666', 'Airbus A320', 180, id FROM airlines WHERE iata_code = 'VJ'
ON CONFLICT (registration_number) DO NOTHING;

INSERT INTO aircraft (registration_number, model, seat_capacity, airline_id)
SELECT 'VN-A590', 'Airbus A320neo', 180, id FROM airlines WHERE iata_code = 'QH'
ON CONFLICT (registration_number) DO NOTHING;

INSERT INTO flights (flight_number, aircraft_id, departure_airport_id, arrival_airport_id, departure_time, arrival_time)
SELECT 'VN210', aircraft.id, departure_airport.id, arrival_airport.id,
       (CURRENT_DATE + INTERVAL '7 days 09:00') AT TIME ZONE 'Asia/Ho_Chi_Minh',
       (CURRENT_DATE + INTERVAL '7 days 11:10') AT TIME ZONE 'Asia/Ho_Chi_Minh'
FROM aircraft
JOIN airports departure_airport ON departure_airport.iata_code = 'SGN'
JOIN airports arrival_airport ON arrival_airport.iata_code = 'HAN'
WHERE aircraft.registration_number = 'VN-A888'
  AND NOT EXISTS (SELECT 1 FROM flights WHERE flight_number = 'VN210');

INSERT INTO flights (flight_number, aircraft_id, departure_airport_id, arrival_airport_id, departure_time, arrival_time)
SELECT 'VJ123', aircraft.id, departure_airport.id, arrival_airport.id,
       (CURRENT_DATE + INTERVAL '7 days 13:30') AT TIME ZONE 'Asia/Ho_Chi_Minh',
       (CURRENT_DATE + INTERVAL '7 days 15:40') AT TIME ZONE 'Asia/Ho_Chi_Minh'
FROM aircraft
JOIN airports departure_airport ON departure_airport.iata_code = 'HAN'
JOIN airports arrival_airport ON arrival_airport.iata_code = 'SGN'
WHERE aircraft.registration_number = 'VN-A666'
  AND NOT EXISTS (SELECT 1 FROM flights WHERE flight_number = 'VJ123');

-- A second SGN -> HAN option on 12 October 2026 for the customer search page.
-- The explicit offset keeps the intended local time independent of the database session timezone.
INSERT INTO flights (flight_number, aircraft_id, departure_airport_id, arrival_airport_id, departure_time, arrival_time)
SELECT 'QH216', aircraft.id, departure_airport.id, arrival_airport.id,
       TIMESTAMPTZ '2026-10-12 14:20:00+07',
       TIMESTAMPTZ '2026-10-12 16:30:00+07'
FROM aircraft
JOIN airports departure_airport ON departure_airport.iata_code = 'SGN'
JOIN airports arrival_airport ON arrival_airport.iata_code = 'HAN'
WHERE aircraft.registration_number = 'VN-A590'
ON CONFLICT (flight_number, departure_time) DO NOTHING;

INSERT INTO flight_fares (flight_id, fare_class_id, price, seat_quota, available_seats)
SELECT flights.id, fare_classes.id, 1500000, 164, 164 FROM flights CROSS JOIN fare_classes
WHERE flights.flight_number = 'VN210' AND fare_classes.code = 'ECONOMY'
ON CONFLICT (flight_id, fare_class_id) DO NOTHING;

INSERT INTO flight_fares (flight_id, fare_class_id, price, seat_quota, available_seats)
SELECT flights.id, fare_classes.id, 4200000, 20, 20 FROM flights CROSS JOIN fare_classes
WHERE flights.flight_number = 'VN210' AND fare_classes.code = 'BUSINESS'
ON CONFLICT (flight_id, fare_class_id) DO NOTHING;

INSERT INTO flight_fares (flight_id, fare_class_id, price, seat_quota, available_seats)
SELECT flights.id, fare_classes.id, 1100000, 180, 180 FROM flights CROSS JOIN fare_classes
WHERE flights.flight_number = 'VJ123' AND fare_classes.code = 'ECONOMY'
ON CONFLICT (flight_id, fare_class_id) DO NOTHING;

INSERT INTO flight_fares (flight_id, fare_class_id, price, seat_quota, available_seats)
SELECT flights.id, fare_classes.id, 1280000, 164, 164 FROM flights CROSS JOIN fare_classes
WHERE flights.flight_number = 'QH216'
  AND flights.departure_time = TIMESTAMPTZ '2026-10-12 14:20:00+07'
  AND fare_classes.code = 'ECONOMY'
ON CONFLICT (flight_id, fare_class_id) DO NOTHING;

INSERT INTO flight_fares (flight_id, fare_class_id, price, seat_quota, available_seats)
SELECT flights.id, fare_classes.id, 3650000, 16, 16 FROM flights CROSS JOIN fare_classes
WHERE flights.flight_number = 'QH216'
  AND flights.departure_time = TIMESTAMPTZ '2026-10-12 14:20:00+07'
  AND fare_classes.code = 'BUSINESS'
ON CONFLICT (flight_id, fare_class_id) DO NOTHING;

COMMIT;
